---
core:
  num_workers: 50


  
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "/home/shebin/NETDEVOPS/Net_automation_Project/Network_Health_Check/hosts.yaml"
    group_file: "/home/shebin/NETDEVOPS/Net_automation_Project/Network_Health_Check/groups.yaml"